#!/usr/bin/env python3
"""
Quick way to get your LinkedIn Person ID

Your LinkedIn person ID is visible in your profile URL or browser console
"""

print("=" * 70)
print("MANUAL: Get your LinkedIn Person ID")
print("=" * 70)
print()
print("METHOD 1: From LinkedIn Profile URL")
print("-" * 70)
print("1. Go to: https://www.linkedin.com/in/YOUR_PROFILE/")
print("2. Check the URL - your ID might be visible there")
print("3. Or use: https://api.linkedin.com/v2/me (if you have access)")
print()
print("METHOD 2: From Browser Console (Developer Tools)")
print("-" * 70)
print("1. Open https://www.linkedin.com (in your browser, logged in)")
print("2. Press F12 to open Developer Tools")
print("3. Go to Console tab")
print("4. Paste this code:")
print()
print('   fetch("https://api.linkedin.com/v2/me", {')
print('     headers: {"Authorization": "Bearer YOUR_TOKEN"}})')
print("     .then(r => r.json())")
print("     .then(d => console.log(d.id))")
print()
print("5. Your person ID will be printed (e.g., ABC123XYZ)")
print()
print("METHOD 3: Use a temporary solution")
print("-" * 70)
print("Post to a company/organization page instead:")
print("LINKEDIN_ORGANIZATION_ID=<your_company_id>")
print()
print("=" * 70)
print("Once you have your Person ID:")
print("=" * 70)
print()
print("Add to .env:")
print("LINKEDIN_PERSON_ID=your_person_id_here")
print()
print("Then run:")
print("python linkedin_poster.py --post-all-drafts")
print()
